webtalk_init -webtalk_dir E:/Documents/Vivado/Basys3/Projects/smvp_systolic/smvp_systolic.sim/sim_1/behav/xsim/xsim.dir/smvp_systolic_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 18 19:38:14 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d22dd6cc-eacf-462c-a6e9-d1e7d0c9a70b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bc1e88127cdc42c7bca36678ddfdd7e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 3900X 12-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3510800 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15956_KB" -context "xsim\\usage"
webtalk_transmit -clientid 779565131 -regid "" -xml E:/Documents/Vivado/Basys3/Projects/smvp_systolic/smvp_systolic.sim/sim_1/behav/xsim/xsim.dir/smvp_systolic_top_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Documents/Vivado/Basys3/Projects/smvp_systolic/smvp_systolic.sim/sim_1/behav/xsim/xsim.dir/smvp_systolic_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Documents/Vivado/Basys3/Projects/smvp_systolic/smvp_systolic.sim/sim_1/behav/xsim/xsim.dir/smvp_systolic_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
